name: Node js app deploy to EKS
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.24.0' # default is latest stable
      id: install

      

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build the aims Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          
          docker build --cache-from $REGISTRY/aimstest/aims:latest -t $REGISTRY/aimstest/aims:$IMAGE_TAG .
          docker tag $REGISTRY/aimstest/aims:$IMAGE_TAG $REGISTRY/aimstest/aims:latest
          docker push $REGISTRY/aimstest/aims:$IMAGE_TAG
          docker push $REGISTRY/aimstest/aims:latest

    # - name: Update kube config
    #   run: aws eks update-kubeconfig --name primuslearning
    
    # - name: Deploy to EKS
    #   run: |
    #     kubectl apply -f deployment.yaml
    #     kubectl apply -f service.yaml
    #       echo Add other actions to build,
    #       echo test, and deploy your project.
